[package]
name = "leet_code"
version = "0.1.0"
authors = ["linguobin <linguobin@bigo.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
